name: Research Project 1
favicon: null
layout_spectrum: 0.74458
typography_spectrum: 0.3579217647202313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#a4a2a7'
    - '#858086'
    - '#715d5e'
    - '#eee5e3'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
