name: Research Project 1
favicon: null
layout_spectrum: 0.7648699516430497
typography_spectrum: 0.3579217647202313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#a4a2a7'
    - '#858086'
    - '#715d5e'
    - '#eee5e3'
  brandStrength: 0.625
  lightness: 0.26862645824439824
  saturation: 0.5002953354269266
  rhythmicContrast: 0.872546121943742
purpose: []
